--liquibase formatted sql
--changeset kaiso:init-property-value author-name:Kais OMRI
--preconditions onFail:HALT onError:HALT
CREATE TABLE LGM_PROPERTY_VALUE (
	ID BIGINT PRIMARY KEY,
	CODE VARCHAR(255),
	CREATEDBY VARCHAR(255),
	CREATEDDATE TIMESTAMP,
	LASTMODIFIEDBY VARCHAR(255),
	LASTMODIFIEDDATE TIMESTAMP,
	DESCRIPTION VARCHAR(500),
	VALUE VARCHAR(1000),
	ENV_ID BIGINT NOT NULL,
	PROP_ID BIGINT NOT NULL,
	CONSTRAINT LGM_PROPERTY_VALUE_FK_LGM_PROPERTY FOREIGN KEY (PROP_ID) REFERENCES LGM_PROPERTY(ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT LGM_PROPERTY_VALUE_FK_LGM_ENVIRONMENT FOREIGN KEY (ENV_ID) REFERENCES LGM_ENVIRONMENT(ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE UNIQUE INDEX UK_LGM_PROPERTY_VALUE_CODE ON LGM_PROPERTY_VALUE (CODE);

