--liquibase formatted sql
--changeset kaiso:init-environment author-name:Kais OMRI
--preconditions onFail:HALT onError:HALT


CREATE TABLE LGM_ENVIRONMENT (
	ID BIGINT PRIMARY KEY,
	CODE VARCHAR(255),
	CREATEDBY VARCHAR(255),
	CREATEDDATE TIMESTAMP,
	LASTMODIFIEDBY VARCHAR(255),
	LASTMODIFIEDDATE TIMESTAMP,
	DESCRIPTION VARCHAR(255),
	NAME VARCHAR(500)
);

CREATE UNIQUE INDEX UK_LGM_ENVIRONMENT_CODE ON LGM_ENVIRONMENT (CODE);
