--liquibase formatted sql
--changeset kaiso:init-property author-name:Kais OMRI
--preconditions onFail:HALT onError:HALT
CREATE TABLE LGM_PROPERTY (
	ID BIGINT PRIMARY KEY,
	CODE VARCHAR(255),
	CREATEDBY VARCHAR(255),
	CREATEDDATE TIMESTAMP,
	LASTMODIFIEDBY VARCHAR(255),
	LASTMODIFIEDDATE TIMESTAMP,
	DESCRIPTION VARCHAR(255),
	NAME VARCHAR(500),
	APP_ID BIGINT NOT NULL,
	CONSTRAINT LGM_PROPERTY_FK_LGM_APPLICATION FOREIGN KEY (APP_ID) REFERENCES LGM_APPLICATION(ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE UNIQUE INDEX UK_LGM_PROPERTY_CODE ON LGM_PROPERTY (CODE);
CREATE UNIQUE INDEX UK_LGM_PROPERTY_KEY ON LGM_PROPERTY (NAME, APP_ID);
