# Site settings
title: Lygeum
email: kais.omri.int@gmail.com
description: >
  Lygeum is a centralized configuration server which comes with a complete toolbox allowing to create, manage and
  quickly and reliably deploy application configurations.
lang: en-US

baseurl: "/lygeum" # the subpath of your site, e.g. /blog/
url: https://kaiso.github.io/lygeum # the base hostname & protocol for your site
git_address: https://github.com/kaiso/lygeum
git_edit_address: https://github.com/kaiso/lygeum/blob/gh-pages

# theme options from https://bootswatch.com/3/
# comment out this to use default Bootstrap
bootwatch: paper # cerulean cosmo custom cyborg darkly flatly journal lumen readable sandstone simplex slate solar spacelab superhero united yeti

# Build settings
markdown: kramdown
highlighter: rouge
# Plugins (previously gems:)
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
  - src/
  - logo_lygeum.docx
  - _docs/examples
  - _docs/customization.md
  - _docs/themes.md
  - _posts/

timezone: Europe/Berlin
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: blog

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true
