name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup JDK
      uses: actions/setup-java@v1.0.0
      with:
       version: 11
    - name: Build
      uses: eskatos/gradle-command-action@v1
      with:
        wrapper-directory: .
        build-root-directory: .
        arguments: clean build
